services:
  unitdogdb:
    image: mysql:latest
    container_name: UnitDb

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Unit-db

    volumes:
      - db-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5


  unitapi:
    build: .
    container_name: UnitApi

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=unitdogdb;Database=Unit-db;Uid=root;Pwd=secret;"

    depends_on:
      unitdogdb:
        condition: service_healthy

volumes:
  db-data: